import fs from "node:fs/promises";
import path from "node:path";
import assert from "node:assert/strict";
import { chromium } from "../node_modules/.cache/feature-tests/node_modules/playwright/index.mjs";
const source = await fs.readFile("src-tauri/src/desktop_features.js", "utf8");
const browser = await chromium.launch({ headless: true, executablePath: process.env.JOKERDECK_BROWSER_EXE });
const page = await browser.newPage({ viewport: { width: 1000, height: 580 }, reducedMotion: "reduce" });
const uuid = "01a0f476-f4c7-7523-b71e-32dd083b2b5b";
const html = `<html><head><meta charset="utf-8"><style>body{margin:0;background:var(--color-background-primary,#fafafa);color:var(--color-text-primary,#333);font:14px system-ui}main{padding:60px 45px}.message{height:170px}h2{font-size:22px}.composer{border:1px solid var(--color-border-primary,#ddd);background:var(--color-background-secondary,#fff);border-radius:22px;padding:16px;box-shadow:0 4px 20px #00000007}.input{height:60px;color:var(--color-text-secondary,#888)}[data-composer-footer-responsive]{display:flex;align-items:center;gap:6px}.control{padding:6px 9px;border:none;border-radius:10px;background:transparent;color:inherit}.access{font-size:12px;color:#d07c00;background:#d07c0010}.send{background:#a93f79;color:white;border-radius:50%;width:29px;height:29px}</style></head><body><main><h2>Codex · 用量与主题</h2><div class="message">当前会话的用量会显示在输入框底部。</div><div class="composer"><div class="input">发送消息...</div><div data-composer-footer-responsive="true"><button class="control">＋</button><button class="control access">◉ 完全访问</button><button class="send">↑</button></div></div></main></body></html>`;
await page.route("http://client-test.local/**", (route) => route.fulfill({ contentType: "text/html", body: html }));
let snapshot = { theme: "rose", overlay: true, today_tokens: 12400, today_cost: .42, total_tokens: 90000, total_cost: 3.25, session_tokens: { total_tokens: 3800, input_tokens: 3000, cached_input_tokens: 2200, output_tokens: 800 }, session_cost: .08, session_cost_complete: false };
await page.route("http://127.0.0.1:39877/snapshot**", (route) => route.fulfill({ json: snapshot, headers: { "access-control-allow-origin": "*" } }));
await page.goto(`http://client-test.local/local/${uuid}`);
await page.evaluate(`(${source})({url:"http://127.0.0.1:39877/snapshot",key:"fixture-only"})`);
await page.waitForFunction(() => document.querySelector('[data-jd="today"]')?.textContent === "12.4K");
assert.equal(await page.locator('[data-jd="session"]').textContent(), "3.8K");
assert.equal(await page.locator('[data-jd="session-cost"]').textContent(), "≈$0.08");
assert.equal(await page.locator('[data-composer-footer-responsive] .control').count(), 2);
assert.equal(await page.locator(".send").count(), 1);
await fs.mkdir("node_modules/.cache/feature-previews", { recursive: true });
await page.screenshot({ path: "node_modules/.cache/feature-previews/rose.png" });
// Switching threads must clear prior-thread totals before a new result arrives.
await page.evaluate(() => history.pushState({}, "", "/local/01a1135c-33c9-7990-a8c3-e9e1a97d46c7"));
await page.evaluate(() => document.body.appendChild(document.createElement("div")));
await page.waitForFunction(() => document.querySelector('[data-jd="session"]')?.textContent === "—");
snapshot = { theme: "midnight", overlay: true, error: "请登录", session_tokens: null };
await page.waitForFunction(() => document.querySelector("#jokerdeck-codex-theme")?.textContent.includes("#131927"), { timeout: 12000 });
await page.screenshot({ path: "node_modules/.cache/feature-previews/midnight.png" });
assert.equal(await page.locator('[data-jd="session-cost"]').textContent(), "—");
snapshot = { theme: "native", overlay: false };
await page.waitForFunction(() => document.querySelector(".jd-usage")?.style.display === "none", { timeout: 12000 });
assert.equal(await page.locator("#jokerdeck-codex-theme").textContent(), "");
await browser.close();
console.log("PASS: footer controls, totals, partial/unknown costs, thread switch, theme switch/restore, overlay toggle");
